_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
            "2":
                - 1
                - 2
                - 3
                - 55
            "3":
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.10.13
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
entropy:
    value: 0.1
lr:
    value: 0.001
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 80000
